### ISSUE TITLE
2.0 Roadmap

### ISSUE THREAD

**Issue by BB9z** [BB9z/RFKit#1]
- [x] Remove all deprecated code.
- [x] doc to wiki
- [x] Merge RFUI/Core
- [x] CI
- [x] Lisence file rename
- [x] change log file
- [x] Swift enhance
